name: Docker build and image publish

on:
  push:
    tags:
      - v*

jobs:
  version:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_DOCKER }}
      - id: get_version
        uses: battila7/get-version-action@v2
      - uses: actions/checkout@v2
        with:
          repository: 'cloudflare/cloudflared'
          ref: ${{ steps.get_version.outputs.version-without-v }}
          path: 'cloudflared'
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm,linux/arm64
          tags: us.gcr.io/mywanderings/cloudflared:latest,us.gcr.io/mywanderings/cloudflared:${{ steps.get_version.outputs.version-without-v }}
          push: true