name: Check upstream version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Tailscale version from source
        run: echo "TSTAG=$(curl https://api.github.com/repos/cloudflare/cloudflared/tags -s | jq '.[0].name' -r)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Update README.md
        run: ./update_readme.sh

      - name: Check updated version and tag
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'update to cloudflared ${{ env.TSTAG }}'
          branch: master
          tag: "v${{ env.TSTAG }}"